@startuml

class com.springboot.MyTodoList.config.BotProps {
	{field} +name : String
	{field} +token : String
}


class com.springboot.MyTodoList.config.CorsConfig {
	{field} ~logger : org.slf4j.Logger
	{method} +corsFilter () : org.springframework.web.filter.CorsFilter
}


class com.springboot.MyTodoList.config.DbSettings {
	{field} +driver_class_name : String
	{field} +password : String
	{field} +url : String
	{field} +username : String
}


class com.springboot.MyTodoList.config.DeepSeekConfig {
	{field} -apiKey : String
	{method} +deepSeekRequest ( apiUrl : String ) : org.apache.hc.client5.http.classic.methods.HttpPost
	{method} +httpClient () : org.apache.hc.client5.http.impl.classic.CloseableHttpClient
}


class com.springboot.MyTodoList.config.OracleConfiguration {
	{field} -dbPassword : String
	{field} -dbUrl : String
	{field} -dbUser : String
	{field} -driverClassName : String
	{field} ~logger : org.slf4j.Logger
	{field} -tnsAdmin : String
	{method} +dataSource () : javax.sql.DataSource
}


class com.springboot.MyTodoList.config.SpaForwardController {
	{method} +forward () : String
}


class com.springboot.MyTodoList.security.WebSecurityConfiguration {
	{method} +passwordEncoder () : org.springframework.security.crypto.password.PasswordEncoder
	{method} +securityFilterChain ( http : org.springframework.security.config.annotation.web.builders.HttpSecurity ) : org.springframework.security.web.SecurityFilterChain
}






@enduml